# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  default

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub-connection'
    repository: 'jofin/ngnix'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: CmdLine@2
  inputs:
    script: 'docker run -p 80:80 -d jofin/nginx:$(Build.BuildId)'